import { ADMIN_PROFILE_GET, CHANGE_PASSWORD_PATCH, FORGOT_PASSWORD_POST, LOGIN_POST, LOGOUT_DELETE, RESEND_EMAIL_POST, RESET_PASSWORD_POST, TOKEN_POST, UPDATE_PROFILE } from "@/constants/api-endpoints";

export type ApiEndpoint =
  | typeof LOGIN_POST
  | typeof LOGOUT_DELETE
  | typeof FORGOT_PASSWORD_POST
  | typeof RESEND_EMAIL_POST
  | typeof RESET_PASSWORD_POST
  | typeof TOKEN_POST
  | typeof ADMIN_PROFILE_GET
  | typeof UPDATE_PROFILE
  | typeof CHANGE_PASSWORD_PATCH
